### ISSUE TITLE
about distributed training

### ISSUE THREAD

**Issue by sorrowyn** [plemeri/UACANet#5]

**Comment by plemeri** [comment]
Hello, thank you for your interest.
Actually, it is not tested yet since I ended up with not using the distributed training, but you may use following command for two GPUs,
`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=$RANDOM train.py --config configs/UACANet-L.yaml --verbose --debug`

Also, note that you may not use `Expr.py`; instead, just run `run/Test.py` and `run/Eval.py` each.

Let me know if there's still problem.

**Comment by sorrowyn** [comment]
Hello @plemeri.Thank you for your help.
In general, distributed training allows each GPU to allocate the same size of memory. But.
![图片](https://user-images.githubusercontent.com/19569162/142517516-00a32583-a819-4ee0-91dd-064fbb0e3ece.png)

**Comment by plemeri** [comment]
I'm currently unable to access any GPU server at this moment, so I'll check if there's any issue.
Besides, it looks like you have RTX 3090 which should be sufficient to train our network with only single device, so until then, you can use them individually.

Thanks!
